services:
  db:
    image: postgres:15-alpine
    container_name: wd-postgres
    restart: always
    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_password
      POSTGRES_DB: monitor_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wd-monitor:
    build: .
    image: wd-monitor:dev
    container_name: wd-monitor:dev
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://monitor_user:monitor_password@db:5432/monitor_db
    volumes:
      #Local PC files
      - ./templates:/app/templates
      - ./static:/app/static
      - ./app.py:/app/app.py
      - ./backend:/app/backend
      - ./catalog.json:/app/catalog.json

volumes:
  pgdata: