services:
  wd-monitor:
    build: .
    image: wd-monitor:latest
    container_name: wd-monitor
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - wd_data:/data

volumes:
  wd_data: