version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: wd-postgres
    restart: always
    environment:
      POSTGRES_USER: monitor_user
      POSTGRES_PASSWORD: monitor_password
      POSTGRES_DB: monitor_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wd-monitor:
    build: .
    container_name: wd-monitor
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://monitor_user:monitor_password@db:5432/monitor_db
      - URL_TARGET=https://www.westerndigital.com/pl-pl/products/internal-drives/wd-red-pro-sata-hdd?sku=WD8005FFBX
      - CHECK_INTERVAL_SECONDS=60

volumes:
  pgdata:
